version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/front-end"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/back-end"
    schedule:
      interval: "weekly"
